AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function for RAG Application with Bedrock and RDS Integration'

Parameters:
  ProjectName:
    Type: String
    Default: 'rag-app'
    Description: 'Name of the project'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  
  AWSRegion:
    Type: String
    Default: 'us-east-1'
    Description: 'AWS region'
  
  VpcId:
    Type: String
    Description: 'VPC ID from VPC stack'
  
  PrivateSubnet1Id:
    Type: String
    Description: 'Private Subnet 1 ID from VPC stack'
  
  PrivateSubnet2Id:
    Type: String
    Description: 'Private Subnet 2 ID from VPC stack'
  
  RDSSecurityGroupId:
    Type: String
    Description: 'RDS Security Group ID from RDS stack'
  
  DBClusterEndpoint:
    Type: String
    Description: 'RDS Cluster Endpoint from RDS stack'
  
  DBName:
    Type: String
    Description: 'Database name from RDS stack'
  
  DBSecretArn:
    Type: String
    Description: 'ARN of database secret in Secrets Manager'
  
  KBId:
    Type: String
    Description: 'Bedrock Knowledge Base ID (create manually or via separate stack)'
  
  ModelId:
    Type: String
    Default: 'anthropic.claude-3-5-sonnet-20240620-v1:0'
    Description: 'Bedrock Model ID'
  
  DefaultTopK:
    Type: Number
    Default: 6
    Description: 'Default number of retrieval results'
  
  ECRImageUri:
    Type: String
    Description: 'ECR image URI for the Lambda container (e.g., 123456789012.dkr.ecr.us-east-1.amazonaws.com/rag-app:latest)'
  
  LambdaMemorySize:
    Type: Number
    Default: 512
    Description: 'Lambda memory size in MB'
  
  LambdaTimeout:
    Type: Number
    Default: 300
    Description: 'Lambda timeout in seconds'

Resources:
  # Lambda Security Group
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${Environment}-lambda-sg'
      GroupDescription: 'Security group for Lambda function'
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'
          Description: 'Allow all outbound traffic'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-lambda-sg'

  # Security Group Rule: Allow Lambda to access RDS
  LambdaToRDSSecurityGroupRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RDSSecurityGroupId
      SourceSecurityGroupId: !Ref LambdaSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      Description: 'Allow PostgreSQL access from Lambda'

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-lambda-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: !Sub 'arn:aws:bedrock:${AWSRegion}::foundation-model/${ModelId}'
              - Effect: Allow
                Action:
                  - bedrock-agent-runtime:Retrieve
                Resource: '*'
                  # TODO: Scope down to specific KB ARN when available
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DBSecretArn
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWSRegion}:*:log-group:/aws/lambda/${ProjectName}-${Environment}-*'

  # CloudWatch Log Group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-chat-app'
      RetentionInDays: 14

  # Lambda Function
  ChatAppLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-chat-app'
      Description: 'RAG Chat Application Lambda Function'
      PackageType: Image
      ImageUri: !Ref ECRImageUri
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          AWS_REGION: !Ref AWSRegion
          KB_ID: !Ref KBId
          MODEL_ID: !Ref ModelId
          PG_DSN: !Sub 'postgresql://{{resolve:secretsmanager:${DBSecretArn}:SecretString:username}}:{{resolve:secretsmanager:${DBSecretArn}:SecretString:password}}@${DBClusterEndpoint}:5432/${DBName}'
          DEFAULT_TOP_K: !Ref DefaultTopK
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1Id
          - !Ref PrivateSubnet2Id
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-chat-app'

Outputs:
  LambdaFunctionArn:
    Description: 'ARN of the Lambda function'
    Value: !GetAtt ChatAppLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'
  
  LambdaFunctionName:
    Description: 'Name of the Lambda function'
    Value: !Ref ChatAppLambda
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName'
  
  LambdaExecutionRoleArn:
    Description: 'ARN of the Lambda execution role'
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRoleArn'

