AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master CloudFormation Template for RAG Application - Orchestrates VPC, RDS, and Lambda Stacks'

# NOTE: This template provides a deployment guide and nested stack structure.
# For modular deployment, deploy stacks in this order:
# 1. vpc-infrastructure.yaml
# 2. rds-postgres.yaml (requires VPC outputs)
# 3. lambda-function.yaml (requires VPC and RDS outputs)

Parameters:
  ProjectName:
    Type: String
    Default: 'rag-app'
    Description: 'Name of the project'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  
  AWSRegion:
    Type: String
    Default: 'us-east-1'
    Description: 'AWS region'
  
  KBId:
    Type: String
    Description: 'Bedrock Knowledge Base ID (create manually or via separate stack)'
  
  ModelId:
    Type: String
    Default: 'anthropic.claude-3-5-sonnet-20240620-v1:0'
    Description: 'Bedrock Model ID'
  
  ECRImageUri:
    Type: String
    Description: 'ECR image URI for the Lambda container'

Resources:
  # Nested Stack: VPC Infrastructure
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc-infrastructure.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AWSRegion: !Ref AWSRegion

  # Nested Stack: RDS PostgreSQL (depends on VPC)
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: rds-postgres.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  # Nested Stack: Lambda Function (depends on VPC and RDS)
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - RDSStack
    Properties:
      TemplateURL: lambda-function.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AWSRegion: !Ref AWSRegion
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        RDSSecurityGroupId: !GetAtt RDSStack.Outputs.RDSSecurityGroupId
        DBClusterEndpoint: !GetAtt RDSStack.Outputs.DBClusterEndpoint
        DBName: !GetAtt RDSStack.Outputs.DBName
        DBSecretArn: !GetAtt RDSStack.Outputs.DBSecretArn
        KBId: !Ref KBId
        ModelId: !Ref ModelId
        ECRImageUri: !Ref ECRImageUri

Outputs:
  VPCId:
    Description: 'VPC ID'
    Value: !GetAtt VPCStack.Outputs.VpcId
  
  DBClusterEndpoint:
    Description: 'Aurora Cluster Endpoint'
    Value: !GetAtt RDSStack.Outputs.DBClusterEndpoint
  
  LambdaFunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
  
  LambdaFunctionName:
    Description: 'Lambda Function Name'
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionName
