AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Policy for accessing AWS Secrets Manager - Database Credentials'

Parameters:
  ProjectName:
    Type: String
    Default: 'chat-template'
    Description: 'Name of the project'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  
  AWSRegion:
    Type: String
    Default: 'us-east-1'
    Description: 'AWS region'

Resources:
  SecretsManagerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${ProjectName}-${Environment}-evals-secrets-manager-policy'
      Description: 'Policy for accessing database credentials from AWS Secrets Manager'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSecretsManagerRead
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              # Pattern from db_secret_template.yaml: ${ProjectName}-${SecretName}-${Environment}
              # Supports secrets like: chat-template-db-connection-dev, chat-template-rag-chat-db-connection-dev
              - !Sub 'arn:aws:secretsmanager:${AWSRegion}:${AWS::AccountId}:secret:${ProjectName}-*-${Environment}-*'

Outputs:
  PolicyArn:
    Description: 'ARN of the Secrets Manager policy'
    Value: !Ref SecretsManagerPolicy
    Export:
      Name: !Sub '${AWS::StackName}-SecretsManagerPolicyArn'

