# Secrets Template
# Copy this file to {env}_secrets.yaml (e.g., dev_secrets.yaml) and fill in values
# DO NOT commit environment-specific secrets files to version control
#
# Usage:
#   cp template.secrets.yaml dev_secrets.yaml
#   # Edit dev_secrets.yaml with your actual values
#
# To push these secrets to GitHub environment secrets (for deploy/run-evals workflows):
#   ./scripts/setup/setup_github.sh   (deploys secrets by default; use --skip-secrets to skip)

# Database credentials (used locally and can be synced to GitHub as MASTER_DB_*)
database:
  master_username: postgres
  master_password: "<your-secure-password>"

# API Keys (if needed by your application)
api_keys:
  openai_api_key: "<your-openai-key>"
  anthropic_api_key: "<your-anthropic-key>"

# GitHub configuration (for OIDC setup)
github:
  org: "<your-github-org>"
  repo: "<your-github-repo>"

# -----------------------------------------------------------------------------
# GitHub environment secrets (deploy.yml, run-evals.yml)
# Sync to GitHub with: ./scripts/setup/setup_github.sh
# See docs/github_environment_secrets.md for names and when each is required.
# -----------------------------------------------------------------------------
github_environment_secrets:
  # Required for deploy workflow (OIDC)
  AWS_DEPLOYER_ROLE_ARN: "<arn:aws:iam::ACCOUNT:role/your-deployer-role>"
  # Optional; defaults to us-east-1 in workflow
  AWS_REGION: "us-east-1"
  # Required when deploying Lambda (skip_lambda is false)
  S3_APP_CONFIG_URI: "<s3://bucket/key or leave empty if not deploying Lambda>"
  # Optional
  LOCAL_APP_CONFIG_PATH: ""
  # DB (optional; can also come from database.* above)
  MASTER_DB_USERNAME: "postgres"
  MASTER_DB_PASSWORD: "<your-secure-password>"
  # When skip_network is true and skip_db is false
  # VPC_ID: "<vpc-...>"
  # SUBNET_IDS: "<subnet-1,subnet-2>"
  # When skip_network is true and deploying Lambda
  # SECURITY_GROUP_IDS: "<sg-...>"

# For staging only: used by run-evals workflow
# AWS_EVALS_ROLE_ARN: "<arn:aws:iam::ACCOUNT:role/your-evals-role>"

# Add other sensitive values as needed below
# custom:
#   my_secret: "<your-secret-value>"
