AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Secrets Manager Secret for Aurora PostgreSQL Database Connection'

Parameters:
  ProjectName:
    Type: String
    Default: 'python-template'
    Description: 'Name of the project'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  
  SecretName:
    Type: String
    Default: 'rag-chat-db-connection'
    Description: 'Name of the secret in AWS Secrets Manager'
  
  DBHost:
    Type: String
    Description: 'Database host endpoint (from DB stack output)'
  
  DBPort:
    Type: Number
    Default: 5432
    Description: 'Database port'
  
  DBName:
    Type: String
    Default: 'rag_chat_db'
    Description: 'Database name'
  
  DBUsername:
    Type: String
    NoEcho: true
    Description: 'Database username'
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'Database password'
    MinLength: 8

Resources:
  # Secrets Manager Secret for DB Connection
  DBConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-${SecretName}-${Environment}'
      Description: !Sub 'Database connection credentials for ${ProjectName}-${Environment}'
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}",
          "engine": "postgres",
          "host": "${DBHost}",
          "port": ${DBPort},
          "dbname": "${DBName}",
          "dbInstanceIdentifier": "${ProjectName}-light-db-cluster-${Environment}"
        }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${SecretName}-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  SecretArn:
    Description: 'ARN of the database connection secret'
    Value: !Ref DBConnectionSecret
    Export:
      Name: !Sub '${AWS::StackName}-SecretArn'
  
  SecretName:
    Description: 'Name of the secret'
    Value: !Ref DBConnectionSecret
    Export:
      Name: !Sub '${AWS::StackName}-SecretName'

